language: r
cache: packages
sudo: required
warnings_are_errors: false

addons:
  apt:
    packages:
      - libgsl0-dbg
      - libgsl0-dev
      - libgsl0ldbl
    update: true

env:
  matrix:
    - r: release
      not_cran: false
      r_check_args: "--no-manual --as--cran"
    - r: devel
      not_cran: false
      r_check_args: "--no-manual --as--cran"