language: r
cache: packages
sudo: required
warnings_are_errors: false

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install texlive-latex-base
  - sudo apt-get install gsl-bin libgsl0-dev

r_packages:
  - covr

matrix:
  include:
  - r: devel
  - r: release
    after_success:
    - R CMD INSTALL .
    - Rscript -e 'pkgdown::build_site(examples = FALSE)'
    - Rscript -e 'library(covr); codecov()'
    deploy:
      provider: pages
      skip-cleanup: true
      github-token: $GITHUB_PAT
      keep-history: true
      local-dir: docs
      on:
        branch: master
