language: r
cache: packages
sudo: false
warnings_are_errors: false

env:
  global:
    - R_CHECK_ARGS="--no-build-vignettes --manual"


addons:
  apt:
    packages:
      - libgsl0-dbg
      - libgsl0-dev
      - libgsl0ldbl
    update: true
